import "./globals.css";
import { Inter } from "next/font/google";
import { QueryProvider } from "./Context";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="theme-color" content="#f69435" />
        <meta name="apple-mobile-web-app-status-bar-style" content="#f69435" />
        <link rel="manifest" href="/manifest.json" />
        {/* Add any other meta tags, title, and description you need */}
      </Head>
      <body className={inter.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
